/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/rileymcmaster/Documents/Personal/Web/Debris/Scan/JRM/jrm_3_mixrig_8.glb --transform --simplify 
Files: /Users/rileymcmaster/Documents/Personal/Web/Debris/Scan/JRM/jrm_3_mixrig_8.glb [30.03MB] > /Users/rileymcmaster/Projects/Personal/threejs/all-eyes/public/assets/models/jrm_3_mixrig_8-transformed.glb [1.64MB] (95%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/jrm_3_mixrig_8-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="jrm" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh name="jrm-mesh" geometry={nodes['jrm-mesh'].geometry} material={materials['jrm lo.001']} skeleton={nodes['jrm-mesh'].skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/jrm_3_mixrig_8-transformed.glb')
