/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/rileymcmaster/Documents/Personal/Web/Debris/Scan/basement/export/basement_3_bike_1.glb --transform --simplify 
Files: /Users/rileymcmaster/Documents/Personal/Web/Debris/Scan/basement/export/basement_3_bike_1.glb [4.69KB] > /Users/rileymcmaster/Projects/Personal/threejs/ecctrl/basement_3_bike_1-transformed.glb [3.94KB] (16%)
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const src = "/assets/models/basement_3_bike_2-transformed.glb";
const Bike = (props) => {
	const group = React.useRef();
	const { nodes, materials, animations } = useGLTF(src);
	const { actions, mixer } = useAnimations(animations, group);

	useEffect(() => {
		actions["ride-by"].timeScale = 0.8;
		actions["ride-by"].reset().fadeIn(0.5).play();
	}, [group.current]);

	return (
		<group ref={group} {...props} dispose={null}>
			<mesh name="bike" geometry={nodes.bike.geometry} material={materials["Material_0.007"]} position={[2.331, 0, 0]} rotation={[-Math.PI, 0.016, -Math.PI]} scale={0.9}></mesh>
		</group>
	);
};

useGLTF.preload(src);
export default Bike;
